# Generated by Django 3.0.4 on 2020-04-10 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_type',
            field=models.CharField(blank=True, choices=[('blog', 'Blog post'), ('review', 'Book review'), ('guide', 'Guide')], max_length=6, null=True),
        ),
    ]
