# Generated by Django 3.0.4 on 2020-04-10 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_post_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_type',
            field=models.CharField(choices=[('blog', 'Blog post'), ('review', 'Book review'), ('guide', 'Guide')], max_length=6, null=True),
        ),
    ]
