# Generated by Django 3.0.4 on 2020-04-10 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_remove_post_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_type',
            field=models.CharField(choices=[('blog', 'Blog post'), ('guide', 'Guide'), ('review', 'Book review')], max_length=6, null=True),
        ),
    ]
