# Generated by Django 3.0.4 on 2020-04-17 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_post_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_type',
            field=models.CharField(choices=[('space_station', 'Space Station'), ('hurricane_and_typhoon_updates', 'Hurricane And Typhoon Updates'), ('earth_day_countdown', 'Earth Day Countdown')], max_length=100, null=True),
        ),
    ]
